contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 3ef08b51-0c3e-4639-8706-ea85e9cef273
inputs: []
name: ROY_TEST_PLAYBOOK
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b622e2fc-0e3c-4f1e-87d9-82a3d518a29b
      iscommand: false
      name: ""
      version: -1
    taskid: b622e2fc-0e3c-4f1e-87d9-82a3d518a29b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 17ba97fe-1976-46ff-8480-3a26b3af632f
      iscommand: false
      name: Task1
      type: regular
      version: -1
    taskid: 17ba97fe-1976-46ff-8480-3a26b3af632f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a84f569e-2f4e-42e3-885d-3747d168a30c
      iscommand: false
      name: Task2
      type: regular
      version: -1
    taskid: a84f569e-2f4e-42e3-885d-3747d168a30c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 500
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c7b8230f-0c80-4c55-820e-b315ac04b8c1
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: c7b8230f-0c80-4c55-820e-b315ac04b8c1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
