contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 6549ac4d-6b8a-4443-8998-0d11e80c8a71
inputs: []
name: ROY_Playbook1
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7d51b3c6-02ac-482f-8a00-38c7da3c0892
      iscommand: false
      name: ""
      version: -1
    taskid: 7d51b3c6-02ac-482f-8a00-38c7da3c0892
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0af371fa-a795-4389-8964-2e3cccdb1e4a
      iscommand: false
      name: Task1
      type: regular
      version: -1
    taskid: 0af371fa-a795-4389-8964-2e3cccdb1e4a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 777e9ed4-077d-4c09-8470-371b81e9a592
      iscommand: false
      name: Task2
      type: regular
      version: -1
    taskid: 777e9ed4-077d-4c09-8470-371b81e9a592
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 599f2285-c46b-48a1-86f9-278f1a1b864b
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 599f2285-c46b-48a1-86f9-278f1a1b864b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 600
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
